# action.yml
name: 'Set CodeQL Languages'
description: 'Auto-populate the Actions matrix definition to include languages for CodeQL'
icon: lock
inputs:
  access-token:  
    description: 'github token'
    required: true
  endpoint:
    description: 'languages API endpoint'
    required: true
  exclude:
    description: 'Use a comma separated list here to exclude specific languges from your CodeQL scan.  Example: "python, java"'
    required: false
  build-mode-manual-override:
    description: 'Use a comma separated list here to specify languages that should use manual build mode instead of the default. Example: "python, ruby"'
    required: false
outputs:
  matrix:
    description: 'Matrix definition including language and build-mode configurations'
  languages:
    description: 'List of languages that will set the job matrix (deprecated - use matrix instead)'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
   - ${{ inputs.access-token }}
   - ${{ inputs.endpoint }}
   - ${{ inputs.exclude }}
   - ${{ inputs.build-mode-manual-override }}

