# action.yml
name: 'Set CodeQL Languages'
description: 'Auto-populate the Actions matrix definition to include languages for CodeQL'
inputs:
  access-token:  
    description: 'github token'
    required: true
  endpoint:
    description: 'languages API endpoint'
    required: true
  excluded-languages:
    description: 'Use a list here to exclude specific languges from your CodeQL scan.  Example: ["python", "javascript"]'
    required: false
    # default: ''
outputs:
  languages:
    description: 'List of languages that will set the job matrix'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
   - ${{ inputs.access-token }}
   - ${{ inputs.endpoint }}
   - ${{ inputs.excluded-languages }}

